### PR TITLE
fix: remove redundant imports

### PR DESCRIPTION
**Pull request by srevinsaju**

### CODE REVIEW

**Comment by TheAssassin** [comment]
I don't see how these imports are redundant. Mind to explain _how_ they are redundant?

If they're imported in other modules and thus also imported here, I wouldn't consider this redundant. It's more annoying when you have to modify files unrelated to the current change because you remove some the import in another file.

**Comment by srevinsaju** [comment]
Running `flake8`, gives `F401`
```
pyuploadtool/build_systems/github_actions.py:4:1: F401 'github' imported but unused
pyuploadtool/releases_hosting_provider/github_releases.py:8:1: F401 '..exceptions.PyUploadtoolError' imported but unused
```

**Comment by TheAssassin** [comment]
Indeed, you are right. Especially the first one makes sense, thinking about it.

I found a few more even:

```
pyuploadtool/__init__.py:1:1: F401 '.types.BuildType' imported but unused
pyuploadtool/__init__.py:2:1: F401 '.metadata.update_metadata_with_user_specified_data' imported but unused
```

They make make little sense to have there. If any, they should be imported from the packages directly. Mind to fix them quickly?

**Comment by srevinsaju** [comment]
Yea, sure.

**Pull request merged**
